version: '3.8'

services:
        app:
                build: .
                image: cm-rent:latest
                environment:
                        SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/rentals-app-db
                        SPRING_DATASOURCE_USERNAME: root
                        SPRING_DATASOURCE_PASSWORD: test
                depends_on:
                        - db
                ports:
                        - "8080:8080"

        db:
                image: mysql:latest
                command: --default-authentication-plugin=mysql_native_password
                restart: always
                environment:
                        MYSQL_ROOT_PASSWORD: test
                        MYSQL_DATABASE: rentals-app-db
                ports:
                        - "3307:3306"

        adminer:
                image: adminer
                restart: always
                ports:
                        - "8086:8080"
